services:
  # Go (Echo) サーバー
  go:
    container_name: go-app
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/go/src/app 
    ports:
      - "8080:8080" 
    networks:
      - common

  # React 開発サーバー
  react:
    container_name: react-app
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - common

  mariadb:
    container_name: db
    image: mariadb:11.0
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: sample
      MARIADB_USER: db-user
      MARIADB_PASSWORD: db-pass
      TZ: 'Asia/Tokyo' 
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - common

volumes:
  dbdata:
    driver: local


networks:
  common:
    driver: bridge