services:
  # Go (Echo) サーバー
  go:
    container_name: go-app
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/go/src/app 
    ports:
      - "8080:8080" 
    networks:
      - common
    depends_on:
      - postgres

  # React 開発サーバー
  react:
    container_name: react-app
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - common

  postgres:
    container_name: db-postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: db-pass
      POSTGRES_DB: sample
      TZ: 'Asia/Tokyo'
    volumes:
      - db-postgres:/var/lib/postgresql/data
    networks:
      - common

volumes:
  db-postgres:
    driver: local


networks:
  common:
    driver: bridge