build_dir = "tmp" 

cmd = "go run main.go"

include_ext = ["go", "tpl", "tmpl", "html"]

exclude_dir = ["assets", "tmp", "vendor"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false